version: "3.8"

services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/development/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql
      - php-fpm

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/development/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-app}
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_URL: ${AWS_URL}
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/development/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-app}
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_URL: ${AWS_URL}
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql

  node-cli:
    build:
      context: docker
      dockerfile: node/development/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_URL: ${AWS_URL}
    volumes:
      - ./laravel:/var/www/laravel

  node-dev-server:
    build:
      context: docker
      dockerfile: node/development/Dockerfile
    command: npm run dev
    tty: true
    ports:
      - "3000:3000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_URL: ${AWS_URL}
    volumes:
      - ./laravel:/var/www/laravel

  mysql:
    image: "mysql/mysql-server:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - test_db_data:/var/lib/mysql

  minio:
    image: "minio/minio"
    entrypoint: minio server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - test_minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      start_period: 1s
      interval: 5s
      timeout: 3s
      retries: 3

  create-bucket:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/$${AWS_BUCKET};
      /usr/bin/mc anonymous set public myminio/$${AWS_BUCKET};
      exit 0;"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
    depends_on:
      - minio

volumes:
  test_db_data:
    name: test_db_data
  test_minio_data:
    name: test_minio_data

networks:
  default:
    name: test_network
    driver: bridge