version: "3.8"

services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/development/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql
      - api-php-fpm

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/development/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-app}
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/development/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-app}
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - mysql

  node-cli:
    build:
      context: docker
      dockerfile: node/development/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./laravel:/var/www/laravel

  node-dev-server:
    build:
      context: docker
      dockerfile: node/development/Dockerfile
    command: npm run dev
    tty: true
    ports:
      - "3000:3000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./laravel:/var/www/laravel

  mysql:
    image: "mysql/mysql-server:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - test_db_data:/var/lib/mysql

volumes:
  test_db_data:
    name: test_db_data

networks:
  default:
    name: test_network
    driver: bridge